-- Add 10 new products (batch 2)
INSERT INTO products (name, description, price, category, weight_kg, in_stock, care_instructions) VALUES
('Hexagonal Pastel Plates', 'A stunning collection of hexagonal plates featuring playful two-tone glazes in soft pastels - teal, blush pink, and warm brown. Perfect for elegant entertaining or everyday dining.', 3800, 'Tableware', 1.5, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Songbird Tea Set', 'An enchanting tea set with delicate bird finials on the lids. Features a bamboo-wrapped handle teapot and matching cups in soft gradient glazes. Makes teatime feel like a garden moment.', 4200, 'Tableware', 1.6, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Ocean Palette Bowls', 'A set of four nesting bowls in vibrant ocean-inspired glazes - deep turquoise, seafoam green, blush pink, and sandy brown. Each bowl features a unique crystalline interior.', 2400, 'Tableware', 0.8, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Praying Hands Collection', 'A set of four sculptural hand dishes in varying finishes - white, terracotta, coral, and speckled cream. Perfect as jewelry holders, trinket dishes, or decorative art pieces.', 3200, 'Artifacts', 0.9, true, 'Clean with damp cloth followed by dry cloth'),
('Terracotta Fruit Bowls', 'Large, generous fruit bowls with raw terracotta exteriors and golden-speckled interior glaze. The hand-carved base adds tactile beauty to this functional piece.', 2800, 'Tableware', 1.4, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Bird Lid Storage Jars', 'Charming storage jars with sweet bird finials, paired with small serving bowls in sage green. Perfect for storing tea, spices, or preserves in your kitchen.', 3000, 'Tableware', 1.2, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Turquoise Geometric Mugs', 'A pair of handcrafted mugs in vibrant turquoise with cream wax-resist geometric patterns. Bold, artistic, and perfect for your morning coffee ritual.', 1600, 'Tableware', 0.5, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Ocean Blue Mugs', 'A pair of elegant mugs in deep ocean blue with cloudy variation that mimics the sea. The organic glaze creates a calming, contemplative aesthetic.', 1600, 'Tableware', 0.5, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Ceramic Grater Plates', 'Functional grater plates with a beautiful textured center for grating ginger, garlic, or citrus zest. The organic edge and warm brown glaze make them display-worthy.', 1400, 'Tableware', 0.6, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Cloud Serving Platters', 'Ethereal white serving platters with organic cloud-like edges and a footed cake stand. Perfect for entertaining, cheese boards, or as stunning centerpieces.', 4500, 'Tableware', 2.0, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity');